### PR TITLE
feature/jvukovich/texture-remapping

### PR DESCRIPTION
**Pull request by jvukovich**
Added a feature so anyone could redefine textures/materials upon conversion using a json structure. This specifically helps me port/convert levels into Unreal Engine using my own preset material/textures. Super handy!

With a few clicks to import into UE, my different textures are auto-resolved:

image

I made the structure a json file so people could potentially re-use this for other games (if possible).

Feel free to hit me up on Discord if necessary, my online handle is Verran.

Thanks! This tool rocks!

### CODE REVIEW

**Comment by jvukovich** [comment]
@arbruijn - does this PR look ok? Any objections/questions/etc? Thank you!

**Comment by arbruijn** [comment]
Thank you for the PR! Looks like a useful feature to add.

I'd prefer to not include the packages folder in the repository though, can you update the PR so it doesn't have the packages/ files?

**Comment by jvukovich** [comment]
@arbruijn Whoops! Will do -- done! Packages folder removed + ignored. Thank you!

**Comment by arbruijn** [comment]
It is released in v1.1.0. Thanks again!

**Pull request merged**
